-- ERAF Commons: Common Code Table
-- 공통코드 관리 테이블
-- Multi-DB Support: PostgreSQL, MySQL, H2

CREATE TABLE IF NOT EXISTS common_code (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_group VARCHAR(100) NOT NULL,
    code VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    sort_order INT DEFAULT 0,
    enabled BOOLEAN DEFAULT true,
    extra_value1 VARCHAR(500),
    extra_value2 VARCHAR(500),
    extra_value3 VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_at TIMESTAMP,
    updated_by VARCHAR(100),
    CONSTRAINT uk_common_code_group_code UNIQUE (code_group, code)
);

CREATE INDEX IF NOT EXISTS idx_common_code_group ON common_code(code_group);
CREATE INDEX IF NOT EXISTS idx_common_code_enabled ON common_code(enabled);

COMMENT ON TABLE common_code IS '공통코드 관리 테이블';
COMMENT ON COLUMN common_code.code_group IS '코드 그룹';
COMMENT ON COLUMN common_code.code IS '코드 값';
COMMENT ON COLUMN common_code.name IS '코드 명칭';
COMMENT ON COLUMN common_code.description IS '코드 설명';
COMMENT ON COLUMN common_code.sort_order IS '정렬 순서';
COMMENT ON COLUMN common_code.enabled IS '사용 여부';
