-- ERAF Commons: Audit Log Table
-- 감사 로그 테이블
-- Multi-DB Support: PostgreSQL, MySQL, H2

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    trace_id VARCHAR(100),
    user_id VARCHAR(100),
    username VARCHAR(100),
    client_ip VARCHAR(45),
    action VARCHAR(100) NOT NULL,
    resource VARCHAR(255) NOT NULL,
    resource_id VARCHAR(255),
    result VARCHAR(50) NOT NULL,
    details TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_log_user_id ON audit_log(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_resource ON audit_log(resource, resource_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_action ON audit_log(action);
CREATE INDEX IF NOT EXISTS idx_audit_log_timestamp ON audit_log(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_trace_id ON audit_log(trace_id);

COMMENT ON TABLE audit_log IS '감사 로그 테이블';
COMMENT ON COLUMN audit_log.timestamp IS '로그 발생 시각';
COMMENT ON COLUMN audit_log.trace_id IS '분산 추적 ID';
COMMENT ON COLUMN audit_log.user_id IS '사용자 ID';
COMMENT ON COLUMN audit_log.username IS '사용자 이름';
COMMENT ON COLUMN audit_log.client_ip IS '클라이언트 IP';
COMMENT ON COLUMN audit_log.action IS '액션 (CREATE, UPDATE, DELETE, LOGIN, LOGOUT, etc.)';
COMMENT ON COLUMN audit_log.resource IS '대상 리소스 타입';
COMMENT ON COLUMN audit_log.resource_id IS '대상 리소스 ID';
COMMENT ON COLUMN audit_log.result IS '결과 (SUCCESS, FAILURE)';
COMMENT ON COLUMN audit_log.details IS '상세 정보 (JSON)';
