-- ERAF Feature Flag: Feature Flags Table
-- 피처 플래그 관리 테이블
-- Multi-DB Support: PostgreSQL, MySQL, H2

CREATE TABLE IF NOT EXISTS feature_flags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flag_key VARCHAR(100) NOT NULL,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(1000),
    enabled BOOLEAN NOT NULL DEFAULT true,
    flag_type VARCHAR(20) NOT NULL DEFAULT 'SIMPLE',
    targeting_rules TEXT,
    fallback_value TEXT,
    tags TEXT,
    metadata TEXT,
    check_count BIGINT DEFAULT 0,
    last_checked_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_at TIMESTAMP,
    updated_by VARCHAR(100),
    CONSTRAINT uk_feature_flags_key UNIQUE (flag_key)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_feature_flags_key ON feature_flags(flag_key);
CREATE INDEX IF NOT EXISTS idx_feature_flags_enabled ON feature_flags(enabled);
CREATE INDEX IF NOT EXISTS idx_feature_flags_type ON feature_flags(flag_type);
CREATE INDEX IF NOT EXISTS idx_feature_flags_created_at ON feature_flags(created_at);

-- Comments
COMMENT ON TABLE feature_flags IS '피처 플래그 관리 테이블';
COMMENT ON COLUMN feature_flags.flag_key IS '고유 피처 플래그 키 (예: new-ui, experimental-api)';
COMMENT ON COLUMN feature_flags.name IS '사람이 읽을 수 있는 피처 플래그 이름';
COMMENT ON COLUMN feature_flags.description IS '피처 플래그 설명';
COMMENT ON COLUMN feature_flags.enabled IS '피처 활성화 여부';
COMMENT ON COLUMN feature_flags.flag_type IS '플래그 타입 (SIMPLE, USER_BASED, PERCENTAGE, TIME_WINDOW, CUSTOM)';
COMMENT ON COLUMN feature_flags.targeting_rules IS '타겟팅 규칙 (JSON, 사용자 기반/비율/시간 조건)';
COMMENT ON COLUMN feature_flags.fallback_value IS '폴백 값 (SpEL 표현식, 선택)';
COMMENT ON COLUMN feature_flags.tags IS '분류용 태그 (JSON 배열)';
COMMENT ON COLUMN feature_flags.metadata IS '추가 메타데이터 (JSON)';
COMMENT ON COLUMN feature_flags.check_count IS '플래그 조회 횟수 (통계)';
COMMENT ON COLUMN feature_flags.last_checked_at IS '마지막 조회 시각';

-- Default Data: Core system flags
INSERT INTO feature_flags (flag_key, name, description, enabled, flag_type)
VALUES
    ('system.maintenance-mode', '유지보수 모드', '시스템 전체 유지보수 모드 활성화 시 사용', false, 'SIMPLE'),
    ('system.debug-logging', '디버그 로깅', '상세 디버그 로그 출력 활성화', false, 'SIMPLE'),
    ('system.rate-limiting', '요청 속도 제한', 'API 요청 속도 제한 기능 활성화', true, 'SIMPLE')
ON CONFLICT (flag_key) DO NOTHING;
