-- ERAF Notification: Notification Templates Table
-- 알림 템플릿 관리 테이블
-- Multi-DB Support: PostgreSQL, MySQL, H2

CREATE TABLE IF NOT EXISTS notification_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_code VARCHAR(100) NOT NULL,
    template_type VARCHAR(20) NOT NULL,
    name VARCHAR(200) NOT NULL,
    subject_template VARCHAR(500),
    body_template TEXT NOT NULL,
    is_html BOOLEAN DEFAULT false,
    locale VARCHAR(10) DEFAULT 'ko',
    active BOOLEAN DEFAULT true,
    description VARCHAR(500),
    required_variables VARCHAR(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(100),
    CONSTRAINT uk_notification_template_code UNIQUE (template_code)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_template_code ON notification_templates(template_code);
CREATE INDEX IF NOT EXISTS idx_template_type ON notification_templates(template_type);
CREATE INDEX IF NOT EXISTS idx_template_active ON notification_templates(active);
CREATE INDEX IF NOT EXISTS idx_template_locale ON notification_templates(locale);

-- Comments
COMMENT ON TABLE notification_templates IS '알림 템플릿 관리 테이블';
COMMENT ON COLUMN notification_templates.template_code IS '템플릿 고유 코드 (예: ORDER_CONFIRMED, PASSWORD_RESET)';
COMMENT ON COLUMN notification_templates.template_type IS '템플릿 유형 (EMAIL, SMS, PUSH, SLACK, TEAMS)';
COMMENT ON COLUMN notification_templates.name IS '템플릿 이름 (관리용)';
COMMENT ON COLUMN notification_templates.subject_template IS '제목 템플릿 (이메일/푸시용, 변수: {{variableName}})';
COMMENT ON COLUMN notification_templates.body_template IS '본문 템플릿 (변수: {{variableName}})';
COMMENT ON COLUMN notification_templates.is_html IS 'HTML 여부 (이메일용)';
COMMENT ON COLUMN notification_templates.locale IS '언어 코드 (ko, en 등)';
COMMENT ON COLUMN notification_templates.active IS '활성 여부';
COMMENT ON COLUMN notification_templates.description IS '템플릿 설명';
COMMENT ON COLUMN notification_templates.required_variables IS '필수 변수 목록 (쉼표 구분)';

-- Default Templates
INSERT INTO notification_templates (template_code, template_type, name, subject_template, body_template, is_html, locale, required_variables)
VALUES
    ('WELCOME_EMAIL', 'EMAIL', '회원가입 환영 이메일',
     '{{serviceName}}에 오신 것을 환영합니다!',
     '안녕하세요 {{userName}}님,\n\n{{serviceName}}에 가입해 주셔서 감사합니다.\n\n즐거운 서비스 이용 되세요!\n\n{{serviceName}} 팀 드림',
     false, 'ko', 'userName,serviceName'),

    ('PASSWORD_RESET', 'EMAIL', '비밀번호 재설정 이메일',
     '[{{serviceName}}] 비밀번호 재설정 안내',
     '안녕하세요 {{userName}}님,\n\n비밀번호 재설정 링크입니다:\n{{resetLink}}\n\n이 링크는 {{expireMinutes}}분 후 만료됩니다.\n\n본인이 요청하지 않으셨다면 이 이메일을 무시하세요.',
     false, 'ko', 'userName,serviceName,resetLink,expireMinutes'),

    ('SYSTEM_ALERT', 'SLACK', '시스템 알림 (Slack)',
     NULL,
     ':warning: *[{{severity}}] {{serviceName}} 시스템 알림*\n\n*메시지*: {{message}}\n*발생 시각*: {{timestamp}}\n*환경*: {{environment}}',
     false, 'ko', 'severity,serviceName,message,timestamp,environment')
ON CONFLICT (template_code) DO NOTHING;
