-- ERAF Notification: Notification History Table
-- 알림 이력 관리 테이블
-- Multi-DB Support: PostgreSQL, MySQL, H2

CREATE TABLE IF NOT EXISTS notification_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_type VARCHAR(20) NOT NULL,
    recipient VARCHAR(500) NOT NULL,
    subject VARCHAR(500),
    message TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    error_message TEXT,
    sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    response_time_ms BIGINT,
    metadata TEXT,
    retry_count INT DEFAULT 0,
    sender VARCHAR(200),
    priority VARCHAR(20) DEFAULT 'NORMAL'
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_notification_type ON notification_history(notification_type);
CREATE INDEX IF NOT EXISTS idx_notification_status ON notification_history(status);
CREATE INDEX IF NOT EXISTS idx_notification_sent_at ON notification_history(sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_notification_recipient ON notification_history(recipient);
CREATE INDEX IF NOT EXISTS idx_notification_priority ON notification_history(priority);

-- Composite index for common query: status + sent_at (데이터 보존 정책 스케줄러용)
CREATE INDEX IF NOT EXISTS idx_notification_status_sent_at ON notification_history(status, sent_at);

-- Comments
COMMENT ON TABLE notification_history IS '알림 전송 이력 테이블';
COMMENT ON COLUMN notification_history.notification_type IS '알림 타입 (EMAIL, SMS, PUSH_FCM, PUSH_APNS, SLACK, TEAMS, WEBHOOK)';
COMMENT ON COLUMN notification_history.recipient IS '수신자 (이메일 주소, 전화번호, 토큰 등)';
COMMENT ON COLUMN notification_history.subject IS '제목 (이메일/푸시알림용)';
COMMENT ON COLUMN notification_history.message IS '알림 메시지 본문';
COMMENT ON COLUMN notification_history.status IS '전송 상태 (PENDING, SUCCESS, FAILED, RETRY)';
COMMENT ON COLUMN notification_history.error_message IS '실패 시 에러 메시지';
COMMENT ON COLUMN notification_history.sent_at IS '전송 시도 시각';
COMMENT ON COLUMN notification_history.completed_at IS '전송 완료 시각';
COMMENT ON COLUMN notification_history.response_time_ms IS '응답 시간 (밀리초)';
COMMENT ON COLUMN notification_history.metadata IS '추가 메타데이터 (JSON)';
COMMENT ON COLUMN notification_history.retry_count IS '재시도 횟수';
COMMENT ON COLUMN notification_history.sender IS '발신자 (이메일인 경우)';
COMMENT ON COLUMN notification_history.priority IS '알림 우선순위 (LOW, NORMAL, HIGH, URGENT)';
