import React, { useState } from 'react';
import { Card, Button, Input, Upload, message, Typography, Tabs, Form, Space, Spin } from 'antd';
import { FilePdfOutlined, DownloadOutlined, UploadOutlined } from '@ant-design/icons';
import { documentApi } from '../../services/api';

const { Title, Text } = Typography;
const { TextArea } = Input;

const PdfPage: React.FC = () => {
  const [loading, setLoading] = useState(false);
  const [form] = Form.useForm();
  const [watermarkText, setWatermarkText] = useState('CONFIDENTIAL');

  const handleGeneratePdf = async (values: any) => {
    setLoading(true);
    try {
      const response = await documentApi.generatePdf(values);
      const blob = new Blob([response.data], { type: 'application/pdf' });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = 'generated.pdf';
      link.click();
      window.URL.revokeObjectURL(url);
      message.success('PDF generated successfully');
    } catch (error) {
      message.error('Failed to generate PDF');
    } finally {
      setLoading(false);
    }
  };

  const handleWatermark = async (file: File) => {
    setLoading(true);
    try {
      const response = await documentApi.addWatermark(file, watermarkText);
      const blob = new Blob([response.data], { type: 'application/pdf' });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = 'watermarked.pdf';
      link.click();
      window.URL.revokeObjectURL(url);
      message.success('Watermark added successfully');
    } catch (error) {
      message.error('Failed to add watermark');
    } finally {
      setLoading(false);
    }
    return false;
  };

  const items = [
    {
      key: '1',
      label: '#5 PDF Generation',
      children: (
        <Card>
          <Title level={5}>Generate PDF Document</Title>
          <Text type="secondary">Create a PDF document with custom content.</Text>
          <Form
            form={form}
            layout="vertical"
            onFinish={handleGeneratePdf}
            style={{ marginTop: 16, maxWidth: 600 }}
            initialValues={{
              title: 'Sample Report',
              content: 'This is a sample PDF document generated by ERAF Framework.',
            }}
          >
            <Form.Item name="title" label="Title" rules={[{ required: true }]}>
              <Input placeholder="Document Title" />
            </Form.Item>
            <Form.Item name="content" label="Content" rules={[{ required: true }]}>
              <TextArea rows={4} placeholder="Document content..." />
            </Form.Item>
            <Form.Item>
              <Button type="primary" htmlType="submit" icon={<DownloadOutlined />} loading={loading}>
                Generate PDF
              </Button>
            </Form.Item>
          </Form>
        </Card>
      ),
    },
    {
      key: '2',
      label: '#6 Template Rendering',
      children: (
        <Card>
          <Title level={5}>Template-based PDF Rendering</Title>
          <Text type="secondary">Generate PDF using predefined templates.</Text>
          <div style={{ marginTop: 16 }}>
            <Button type="primary" icon={<FilePdfOutlined />} disabled>
              Coming Soon
            </Button>
          </div>
        </Card>
      ),
    },
    {
      key: '3',
      label: '#7 Watermark',
      children: (
        <Card>
          <Title level={5}>Add Watermark to PDF</Title>
          <Text type="secondary">Upload a PDF and add a text watermark.</Text>
          <Space direction="vertical" style={{ marginTop: 16 }}>
            <Input
              value={watermarkText}
              onChange={(e) => setWatermarkText(e.target.value)}
              placeholder="Watermark text"
              style={{ width: 300 }}
            />
            <Upload accept=".pdf" beforeUpload={handleWatermark} showUploadList={false}>
              <Button icon={<UploadOutlined />} loading={loading}>
                Upload PDF & Add Watermark
              </Button>
            </Upload>
          </Space>
        </Card>
      ),
    },
  ];

  return (
    <Spin spinning={loading}>
      <Title level={3}>
        <FilePdfOutlined /> PDF Features (#5~#7)
      </Title>
      <Tabs items={items} />
    </Spin>
  );
};

export default PdfPage;
