package com.eraf.sample.controller.document;

import com.eraf.pdf.PdfGenerator;
import jakarta.servlet.http.HttpServletResponse;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import java.io.IOException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Map;

/**
 * PDF 기능 시연 컨트롤러
 * #5 PDF 생성
 * #6 PDF 템플릿 렌더링
 * #7 PDF 워터마크
 */
@Slf4j
@Controller
@RequestMapping("/document/pdf")
public class PdfController {

    @GetMapping
    public String index(Model model) {
        model.addAttribute("menu", "pdf");
        model.addAttribute("title", "PDF - ERAF Sample");
        return "document/pdf";
    }

    /**
     * #5 PDF 생성 - 기본 텍스트 PDF (GET)
     */
    @GetMapping("/generate")
    public void generate(
            @RequestParam(defaultValue = "Hello, ERAF PDF!") String text,
            HttpServletResponse response) throws IOException {
        doGeneratePdf(text, response);
    }

    /**
     * #5 PDF 생성 - 기본 텍스트 PDF (POST for frontend)
     */
    @PostMapping("/generate")
    @ResponseBody
    public byte[] generatePost(@RequestBody Map<String, Object> request) throws IOException {
        String title = (String) request.getOrDefault("title", "ERAF PDF");
        String content = (String) request.getOrDefault("content", "Hello, ERAF PDF!");

        String html = """
                <!DOCTYPE html>
                <html>
                <head>
                    <style>
                        body { font-family: Arial, sans-serif; padding: 40px; }
                        h1 { color: #333; border-bottom: 2px solid #0d6efd; padding-bottom: 10px; }
                        .content { margin-top: 20px; line-height: 1.8; }
                        .footer { margin-top: 40px; color: #666; font-size: 12px; }
                    </style>
                </head>
                <body>
                    <h1>%s</h1>
                    <div class="content">
                        <p>%s</p>
                        <p>Generated at: %s</p>
                    </div>
                    <div class="footer">
                        Generated by ERAF Framework - eraf-pdf module
                    </div>
                </body>
                </html>
                """.formatted(title, content, LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));

        log.info("PDF generated via POST: {}", title);
        return PdfGenerator.fromHtmlToBytes(html, null);
    }

    private void doGeneratePdf(String text, HttpServletResponse response) throws IOException {

        String html = """
                <!DOCTYPE html>
                <html>
                <head>
                    <style>
                        body { font-family: Arial, sans-serif; padding: 40px; }
                        h1 { color: #333; border-bottom: 2px solid #0d6efd; padding-bottom: 10px; }
                        .content { margin-top: 20px; line-height: 1.8; }
                        .footer { margin-top: 40px; color: #666; font-size: 12px; }
                    </style>
                </head>
                <body>
                    <h1>ERAF PDF Generator</h1>
                    <div class="content">
                        <p>%s</p>
                        <p>Generated at: %s</p>
                    </div>
                    <div class="footer">
                        Generated by ERAF Framework - eraf-pdf module
                    </div>
                </body>
                </html>
                """.formatted(text, LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));

        byte[] pdfBytes = PdfGenerator.fromHtmlToBytes(html, null);

        response.setContentType("application/pdf");
        response.setHeader("Content-Disposition", "attachment; filename=\"generated.pdf\"");
        response.getOutputStream().write(pdfBytes);

        log.info("PDF generated successfully");
    }

    /**
     * #6 PDF 템플릿 렌더링
     */
    @GetMapping("/template")
    public void template(
            @RequestParam(defaultValue = "invoice") String type,
            HttpServletResponse response) throws IOException {

        String html = switch (type) {
            case "invoice" -> generateInvoiceHtml();
            case "report" -> generateReportHtml();
            case "certificate" -> generateCertificateHtml();
            default -> generateInvoiceHtml();
        };

        byte[] pdfBytes = PdfGenerator.fromHtmlToBytes(html, null);

        String filename = URLEncoder.encode(type + "_" + System.currentTimeMillis() + ".pdf", StandardCharsets.UTF_8);
        response.setContentType("application/pdf");
        response.setHeader("Content-Disposition", "attachment; filename=\"" + filename + "\"");
        response.getOutputStream().write(pdfBytes);

        log.info("PDF template generated: {}", type);
    }

    /**
     * #7 PDF 워터마크 - HTML CSS로 워터마크 효과
     */
    @GetMapping("/watermark")
    public void watermark(
            @RequestParam(defaultValue = "CONFIDENTIAL") String watermarkText,
            HttpServletResponse response) throws IOException {

        String html = """
                <!DOCTYPE html>
                <html>
                <head>
                    <style>
                        body {
                            font-family: Arial, sans-serif;
                            padding: 40px;
                            position: relative;
                        }
                        .watermark {
                            position: fixed;
                            top: 50%%;
                            left: 50%%;
                            transform: translate(-50%%, -50%%) rotate(-45deg);
                            font-size: 80px;
                            color: rgba(200, 200, 200, 0.3);
                            white-space: nowrap;
                            z-index: -1;
                        }
                        h1 { color: #333; }
                        .content { margin-top: 20px; }
                        table { width: 100%%; border-collapse: collapse; margin-top: 20px; }
                        th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
                        th { background-color: #f5f5f5; }
                    </style>
                </head>
                <body>
                    <div class="watermark">%s</div>
                    <h1>Confidential Document</h1>
                    <div class="content">
                        <p>This document contains sensitive information.</p>
                        <table>
                            <tr><th>Item</th><th>Description</th><th>Status</th></tr>
                            <tr><td>Project Alpha</td><td>Core development</td><td>In Progress</td></tr>
                            <tr><td>Project Beta</td><td>UI/UX Design</td><td>Completed</td></tr>
                            <tr><td>Project Gamma</td><td>Testing Phase</td><td>Pending</td></tr>
                        </table>
                    </div>
                    <div style="margin-top: 40px; color: #666; font-size: 12px;">
                        Generated: %s | Watermark: %s
                    </div>
                </body>
                </html>
                """.formatted(
                watermarkText,
                LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")),
                watermarkText
        );

        byte[] pdfBytes = PdfGenerator.fromHtmlToBytes(html, null);

        response.setContentType("application/pdf");
        response.setHeader("Content-Disposition", "attachment; filename=\"watermarked.pdf\"");
        response.getOutputStream().write(pdfBytes);

        log.info("PDF with watermark generated: {}", watermarkText);
    }

    /**
     * PDF 미리보기 (inline)
     */
    @GetMapping("/preview")
    public void preview(
            @RequestParam(defaultValue = "This is a preview PDF document.") String content,
            HttpServletResponse response) throws IOException {

        String html = """
                <!DOCTYPE html>
                <html>
                <head>
                    <style>
                        body { font-family: Arial, sans-serif; padding: 40px; }
                        h1 { color: #0d6efd; }
                    </style>
                </head>
                <body>
                    <h1>PDF Preview</h1>
                    <p>%s</p>
                    <p><small>Generated at: %s</small></p>
                </body>
                </html>
                """.formatted(content, LocalDateTime.now());

        byte[] pdfBytes = PdfGenerator.fromHtmlToBytes(html, null);

        response.setContentType("application/pdf");
        response.setHeader("Content-Disposition", "inline; filename=\"preview.pdf\"");
        response.getOutputStream().write(pdfBytes);
    }

    private String generateInvoiceHtml() {
        return """
                <!DOCTYPE html>
                <html>
                <head>
                    <style>
                        body { font-family: Arial, sans-serif; padding: 30px; }
                        .header { display: flex; justify-content: space-between; margin-bottom: 30px; }
                        .company { font-size: 24px; font-weight: bold; color: #0d6efd; }
                        .invoice-title { font-size: 28px; color: #333; }
                        table { width: 100%%; border-collapse: collapse; margin-top: 20px; }
                        th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
                        th { background-color: #0d6efd; color: white; }
                        .total { font-size: 18px; font-weight: bold; text-align: right; margin-top: 20px; }
                        .footer { margin-top: 50px; text-align: center; color: #666; font-size: 12px; }
                    </style>
                </head>
                <body>
                    <div class="header">
                        <div class="company">ERAF Corporation</div>
                        <div class="invoice-title">INVOICE</div>
                    </div>
                    <p><strong>Invoice No:</strong> INV-2024-001</p>
                    <p><strong>Date:</strong> %s</p>
                    <p><strong>Customer:</strong> ACME Corporation</p>
                    <table>
                        <tr><th>Item</th><th>Qty</th><th>Unit Price</th><th>Amount</th></tr>
                        <tr><td>ERAF Enterprise License</td><td>1</td><td>$10,000</td><td>$10,000</td></tr>
                        <tr><td>Support Package (1 Year)</td><td>1</td><td>$2,000</td><td>$2,000</td></tr>
                        <tr><td>Training Sessions</td><td>5</td><td>$500</td><td>$2,500</td></tr>
                    </table>
                    <div class="total">Total: $14,500</div>
                    <div class="footer">Thank you for your business!</div>
                </body>
                </html>
                """.formatted(LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd")));
    }

    private String generateReportHtml() {
        return """
                <!DOCTYPE html>
                <html>
                <head>
                    <style>
                        body { font-family: Arial, sans-serif; padding: 30px; }
                        h1 { color: #333; border-bottom: 3px solid #28a745; padding-bottom: 10px; }
                        .section { margin-top: 30px; }
                        .metric { display: inline-block; width: 30%%; text-align: center; padding: 20px; margin: 10px; background: #f8f9fa; border-radius: 8px; }
                        .metric-value { font-size: 32px; font-weight: bold; color: #28a745; }
                        .metric-label { color: #666; }
                        table { width: 100%%; border-collapse: collapse; margin-top: 20px; }
                        th, td { border: 1px solid #ddd; padding: 10px; }
                        th { background-color: #28a745; color: white; }
                    </style>
                </head>
                <body>
                    <h1>Monthly Report - %s</h1>
                    <div class="section">
                        <h2>Key Metrics</h2>
                        <div class="metric"><div class="metric-value">1,234</div><div class="metric-label">Total Users</div></div>
                        <div class="metric"><div class="metric-value">$45.6K</div><div class="metric-label">Revenue</div></div>
                        <div class="metric"><div class="metric-value">98.5%%</div><div class="metric-label">Uptime</div></div>
                    </div>
                    <div class="section">
                        <h2>Performance Summary</h2>
                        <table>
                            <tr><th>Category</th><th>Current</th><th>Previous</th><th>Change</th></tr>
                            <tr><td>API Calls</td><td>1.2M</td><td>1.0M</td><td>+20%%</td></tr>
                            <tr><td>Avg Response Time</td><td>45ms</td><td>52ms</td><td>-13%%</td></tr>
                            <tr><td>Error Rate</td><td>0.1%%</td><td>0.2%%</td><td>-50%%</td></tr>
                        </table>
                    </div>
                </body>
                </html>
                """.formatted(LocalDateTime.now().format(DateTimeFormatter.ofPattern("MMMM yyyy")));
    }

    private String generateCertificateHtml() {
        return """
                <!DOCTYPE html>
                <html>
                <head>
                    <style>
                        body { font-family: 'Times New Roman', serif; padding: 50px; text-align: center; background: linear-gradient(135deg, #f5f7fa 0%%, #c3cfe2 100%%); }
                        .border { border: 3px double #gold; padding: 40px; background: white; }
                        h1 { font-size: 36px; color: #333; margin-bottom: 30px; }
                        .subtitle { font-size: 18px; color: #666; margin-bottom: 40px; }
                        .name { font-size: 28px; font-weight: bold; color: #0d6efd; margin: 30px 0; font-style: italic; }
                        .description { font-size: 16px; color: #444; margin: 20px 0; }
                        .date { margin-top: 40px; color: #666; }
                        .signature { margin-top: 50px; border-top: 1px solid #333; width: 200px; display: inline-block; padding-top: 10px; }
                    </style>
                </head>
                <body>
                    <div class="border">
                        <h1>Certificate of Completion</h1>
                        <div class="subtitle">This is to certify that</div>
                        <div class="name">John Doe</div>
                        <div class="description">
                            has successfully completed the<br>
                            <strong>ERAF Framework Development Course</strong>
                        </div>
                        <div class="date">Date: %s</div>
                        <div class="signature">Authorized Signature</div>
                    </div>
                </body>
                </html>
                """.formatted(LocalDateTime.now().format(DateTimeFormatter.ofPattern("MMMM dd, yyyy")));
    }
}
